Melhora tutorial de luz azul
AmaroJunior98/tutorials pull request #2
Opened 2024-12-04 02:43 UTC by ArthurGorgonio

Dei uma melhorada na doc que ensina a colocar a luz azul. Adicionado também um exemplo de como colocar uma configuração personalizada.

2024-12-14 15:11 UTC, porfirioamarojr commented on manjaro_sway/tutoria_filtro_de_luz_azul_manjaro_com_sway.md
> +  bindsym k exec $kill_gamma, mode 'default'
Esse k aqui pode ser melhorado!

2024-12-14 15:14 UTC, porfirioamarojr requested changes
Comentarios adicionados para melhoria de execução

2024-12-14 18:35 UTC, ArthurGorgonio commented on manjaro_sway/tutoria_filtro_de_luz_azul_manjaro_com_sway.md
> +  bindsym k exec $kill_gamma, mode 'default'
Concordo com você, ele parece solto aí sem necessidade.

2024-12-14 18:59 UTC, ArthurGorgonio commented on manjaro_sway/tutoria_filtro_de_luz_azul_manjaro_com_sway.md
> +  bindsym k exec $kill_gamma, mode 'default'
Acredito que agora esteja okay, adicionei uma explicação sobre o uso com o `&&`. Como no exemplo utilizei o &&, ele obriga que o comando anterior tenha sido executado com sucesso. A outra opção que temos é utilizar o `;`, mas eu preferi manter com o `&&` e adicionar notas para tornar mais completo.

2024-12-27 01:10 UTC, ArthurGorgonio commented
@porfirioamarojr, teve algum outro problema?

2025-01-19 20:14 UTC, ArthurGorgonio commented
@porfirioamarojr, conforme a gente conversou, tente adicionar a execução do gammastep na config do sway, segue um exemplo:
```
set $mode_temp GammaStep: (d)ay, (t)ransition, (n)ight ou (k)ill
# Alterado essa linha, para ser apenas a chamada sem outras configurações
set $gamma gammastep
set $kill_gamma killall gammastep
bindsym $mod+t mode '$mode_temp'
# Adicionado essa linha para realizar a chamada do gammastep durante a inicialização do sway
exec $gamma -O 6500
mode '$mode_temp' {
  bindsym d exec $kill_gamma && $gamma -O 6500, mode 'default'
  bindsym t exec $kill_gamma && $gamma -O 5500, mode 'default'
  bindsym n exec $kill_gamma && $gamma -O 4500, mode 'default'
  bindsym k exec $kill_gamma, mode 'default'
  bindsym Escape mode 'default'
}
```

2025-02-08 01:58 UTC, porfirioamarojr commented
> @porfirioamarojr, teve algum outro problema?



> @porfirioamarojr, conforme a gente conversou, tente adicionar a execução do gammastep na config do sway, segue um exemplo:
> 
> ```
> set $mode_temp GammaStep: (d)ay, (t)ransition, (n)ight ou (k)ill
> # Alterado essa linha, para ser apenas a chamada sem outras configurações
> set $gamma gammastep
> set $kill_gamma killall gammastep
> bindsym $mod+t mode '$mode_temp'
> # Adicionado essa linha para realizar a chamada do gammastep durante a inicialização do sway
> exec $gamma -O 6500
> mode '$mode_temp' {
>   bindsym d exec $kill_gamma && $gamma -O 6500, mode 'default'
>   bindsym t exec $kill_gamma && $gamma -O 5500, mode 'default'
>   bindsym n exec $kill_gamma && $gamma -O 4500, mode 'default'
>   bindsym k exec $kill_gamma, mode 'default'
>   bindsym Escape mode 'default'
> }
> ```
> 
> Se der certo agora, eu atualizo o pull request com essa alteração. Quando fiz os testes aqui, deu tudo certo (gammastep iniciando com a interface, chamadas alternando o valor do gamma).

De acordo com o que foi discutido houve alguns detalhes que precisavam ser resolvidos na inicialização do gammastep, mas nessa ultima alteração tudo funcionou conforme o esperado

2025-02-08 02:00 UTC, ArthurGorgonio commented
> De acordo com o que foi discutido houve alguns detalhes que precisavam ser resolvidos na inicialização do gammastep, mas nessa ultima alteração tudo funcionou conforme o esperado

Beleza, então vou atualizar o repositório com essas adições. Logo mais o PR estará disponível.

2025-02-08 02:06 UTC, merged